config/routes.rb
Rails.application.routes.draw do
  root "homes#index"

  devise_for :users, only: %i[sessions registrations passwords]
  resources :payments
  resources :sales do
    resources :payments, only: [:new, :create]
  end
  resources :stocks
  resources :homes
  resources :products
  resources :customers
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  has_many :payments
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]
  before_action :fetch_customers, only: %i[new edit create update]
  before_action :fetch_products, only: %i[new edit create update]



  # GET /sales or /sales.json
  def index
    @sales = Sale.includes(:payments).all
  end

  # GET /sales/1 or /sales/1.json
  def show
    @payment = Payment.new
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)
    @product = Product.find_by(id: @sale.product_id)

    @sale.total = @product.price * @sale.quantity

    respond_to do |format|
      if @sale.save
        UpdateStock.new(sale_params).call
        format.html { redirect_to sales_path, notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy!

    respond_to do |format|
      format.html { redirect_to sales_path, status: :see_other, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:quantity, :customer_id, :product_id)
    end

    def fetch_customers
      @customers = Customer.all
    end

    def fetch_products
      @products = Product.all
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :customer_id, style: "display: block" %>
    <%= form.select :customer_id, @customers.map{|customer| [customer.name, customer.id]}, include_blank: 'Selecione' %>
  </div>

  <div class="form-group">
    <%= form.label :product_id, style: "display: block" %>
    <%= form.select :product_id, @products.map{|product| [product.name, product.id]}, include_blank: 'Selecione' %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/_sale.html.erb
<div id="<%= dom_id sale %>">
  <p>
    <strong>Quantity:</strong>
    <%= sale.quantity %>
  </p>

</div>

app/views/sales/_table_row.html.erb
<tr>
  <th scope="row"><%= link_to  sale.id.to_s, sale_path(sale), title: 'Ir para pagamento', data: { bs_toggle: "modal", bs_target: "#modal#{sale.id}" }   %></th>
  <td><%= sale.product.name %></td>
  <td><%= sale.quantity %></td>
  <td><%= number_to_currency(sale.total, locale: 'pt-BR') %></td>
  <td>
    <% if sale.payments.any? %>
      <span class="text-success">Pago</span>
    <% else %>
      <%= link_to '<i class="bi bi-cash-coin"></i>'.html_safe, new_sale_payment_path(sale), class: 'btn btn-warning mx-1', title: 'Ir para pagamento' %>
    <% end %>
  </td>
</tr>

<!-- Modal -->
<div class="modal fade" id="modal<%= sale.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Dados da Venda</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Cliente: <%= sale.id %> - <%= sale.customer.name %></p>
        <p>Produto: <%= sale.product.name %></p>
        <p>Quantidade: <%= sale.quantity %></p>
        <p>Valor total: <%= number_to_currency(sale.total, locale: 'pt-BR') %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/sales/edit.html.erb
<% content_for :title, "Editing sale" %>

<h1>Editing sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Show this sale", @sale %> |
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Sales" %>

<h1>Venda</h1>


<%= link_to "Criar venda", new_sale_path, class: 'btn btn-primary' %>



<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Produto</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Valor</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

  <% @sales.each do |sale| %>
    <%= render 'table_row', sale: sale %>
  <% end %>
  </tbody>
</table>

app/views/sales/new.html.erb
<% content_for :title, "New sale" %>

<h1>New sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sale %>

<div>
  <%= link_to "Edit this sale", edit_sale_path(@sale) %> |
  <%= link_to "Back to sales", sales_path %>

  <%= button_to "Destroy this sale", @sale, method: :delete %>
</div>